import React from "react";
import AttendancePieChart from "../../components/employee&target_management/employee/dashboard/RoleWiseAttendance";
import EmployeeBarChart from "../../components/employee&target_management/employee/dashboard/DistributionByStatus";
import EmployeeTable from "../../components/employee&target_management/employee/dashboard/EmployeeList";

const Dashboard = () => {
  // Sample data is defined only in this main page.
  const sampleEmployees = [
    {
      employeeID: "E001",
      firstName: "John",
      lastName: "Doe",
      role: "Tunnel Manager",
      contactNumber: "071-123456",
      status: "Active",
      email: "john.doe@example.com",
      nic: "123456789V",
      address: "123, Main Street, Colombo",
      dateOfBirth: "1985-06-15",
      gender: "Male",
      joiningDate: "2020-01-10",
      employmentType: "Full-time",
      salary: 100000,
      workSchedule: "Morning Shift",
      attendanceRecord: { "2025-03-01": "Present", "2025-03-02": "Absent" },
      performanceScore: 85,
      targetAssigned: 100,
      targetAchieved: 90,
      emergencyContact: { name: "Jane Doe", phone: "077-9876543" },
      supervisorID: "S001",
    },
    {
      employeeID: "E002",
      firstName: "Jane",
      lastName: "Smith",
      role: "Agricultural Technician",
      contactNumber: "077-654321",
      status: "Inactive",
      email: "jane.smith@example.com",
      nic: "987654321V",
      address: "456, Market Road, Kandy",
      dateOfBirth: "1990-04-20",
      gender: "Female",
      joiningDate: "2019-05-22",
      employmentType: "Part-time",
      salary: 75000,
      workSchedule: "Evening Shift",
      attendanceRecord: { "2025-03-01": "Present", "2025-03-02": "Present" },
      performanceScore: 92,
      targetAssigned: 80,
      targetAchieved: 78,
      emergencyContact: { name: "John Smith", phone: "071-5678902" },
      supervisorID: "S002",
    },
    {
      employeeID: "E003",
      firstName: "Alice",
      lastName: "Brown",
      role: "Laborer | Planting & Seeding",
      contactNumber: "070-987654",
      status: "On Leave",
      email: "alice.brown@example.com",
      nic: "567890123V",
      address: "789, Lake Road, Galle",
      dateOfBirth: "1992-09-10",
      gender: "Female",
      joiningDate: "2018-03-15",
      employmentType: "Contract",
      salary: 85000,
      workSchedule: "Night Shift",
      attendanceRecord: { "2025-03-01": "Absent", "2025-03-02": "Present" },
      performanceScore: 88,
      targetAssigned: 90,
      targetAchieved: 85,
      emergencyContact: { name: "Robert Brown", phone: "075-4567890" },
      supervisorID: "S003",
    },
    {
      employeeID: "E004",
      firstName: "Bob",
      lastName: "Johnson",
      role: "Laborer | Pruning & Trimming",
      contactNumber: "075-345678",
      status: "Active",
      email: "bob.johnson@example.com",
      nic: "345678901V",
      address: "101, Hill Street, Matara",
      dateOfBirth: "1988-11-25",
      gender: "Male",
      joiningDate: "2021-07-30",
      employmentType: "Full-time",
      salary: 95000,
      workSchedule: "Morning Shift",
      attendanceRecord: { "2025-03-01": "Present", "2025-03-02": "Present" },
      performanceScore: 90,
      targetAssigned: 110,
      targetAchieved: 105,
      emergencyContact: { name: "Emily Johnson", phone: "076-1234567" },
      supervisorID: "S004",
    },
    {
      employeeID: "E005",
      firstName: "Michael",
      lastName: "Williams",
      role: "Laborer | Harvesting & Packing",
      contactNumber: "072-5555555",
      status: "Active",
      email: "michael.williams@example.com",
      nic: "112233445V",
      address: "222, Green Avenue, Nuwara Eliya",
      dateOfBirth: "1983-12-10",
      gender: "Male",
      joiningDate: "2017-08-15",
      employmentType: "Full-time",
      salary: 120000,
      workSchedule: "Morning Shift",
      attendanceRecord: { "2025-03-01": "Present", "2025-03-02": "Present" },
      performanceScore: 95,
      targetAssigned: 120,
      targetAchieved: 118,
      emergencyContact: { name: "Sarah Williams", phone: "077-8889990" },
      supervisorID: "S005",
    },
    {
      employeeID: "E006",
      firstName: "Emma",
      lastName: "Taylor",
      role: "Laborer | Pest & Disease Control",
      contactNumber: "071-6666666",
      status: "On Leave",
      email: "emma.taylor@example.com",
      nic: "667788990V",
      address: "789, Ocean Road, Negombo",
      dateOfBirth: "1995-07-21",
      gender: "Female",
      joiningDate: "2022-02-11",
      employmentType: "Contract",
      salary: 85000,
      workSchedule: "Evening Shift",
      attendanceRecord: { "2025-03-01": "Absent", "2025-03-02": "Present" },
      performanceScore: 80,
      targetAssigned: 100,
      targetAchieved: 82,
      emergencyContact: { name: "James Taylor", phone: "070-9998887" },
      supervisorID: "S006",
    },
    {
      employeeID: "E007",
      firstName: "David",
      lastName: "Anderson",
      role: "Laborer | Irrigation & Fertilization",
      contactNumber: "076-7777777",
      status: "Inactive",
      email: "david.anderson@example.com",
      nic: "998877665V",
      address: "101, Tech Park, Colombo",
      dateOfBirth: "1991-05-30",
      gender: "Male",
      joiningDate: "2015-10-05",
      employmentType: "Full-time",
      salary: 150000,
      workSchedule: "Morning Shift",
      attendanceRecord: { "2025-03-01": "Present", "2025-03-02": "Absent" },
      performanceScore: 90,
      targetAssigned: 130,
      targetAchieved: 125,
      emergencyContact: { name: "Laura Anderson", phone: "074-5554443" },
      supervisorID: "S007",
    },
    {
      employeeID: "E008",
      firstName: "James",
      lastName: "Hanz",
      role: "Tunnel Manager",
      contactNumber: "076-7777977",
      status: "Inactive",
      email: "james.hanz@example.com",
      nic: "998077665V",
      address: "103, Tech Park, Colombo",
      dateOfBirth: "1995-05-30",
      gender: "Male",
      joiningDate: "2019-10-05",
      employmentType: "Full-time",
      salary: 150000,
      workSchedule: "Morning Shift",
      attendanceRecord: { "2025-03-01": "Present", "2025-03-02": "Absent" },
      performanceScore: 90,
      targetAssigned: 130,
      targetAchieved: 125,
      emergencyContact: { name: "Laura Hanz", phone: "074-5504443" },
      supervisorID: "S007",
    },
    // ... additional sample data (e.g., using Array.from as in your original code)
    ...Array.from({ length: 50 }, (_, index) => ({
      employeeID: `E00${index + 9}`,
      firstName: `Employee${index + 5}`,
      lastName: `Last${index + 5}`,
      role: [ "Supervisor", "Agricultural Technician", "Laborer | Planting & Seeding", "Laborer | Pruning & Trimming", "Laborer | Harvesting & Packing" ][index % 5],
      contactNumber: `07${index + 5}-1111111`,
      status: ["Active", "Inactive", "On Leave"][index % 3],
      email: `employee${index + 5}@example.com`,
      nic: `${index + 100000000}V`,
      address: `${index + 10}, Example Road, City`,
      dateOfBirth: `199${index}-01-01`,
      gender: index % 2 === 0 ? "Male" : "Female",
      joiningDate: `201${index}-05-10`,
      employmentType: index % 2 === 0 ? "Full-time" : "Part-time",
      salary: 80000 + index * 5000,
      workSchedule: ["Morning Shift", "Evening Shift", "Night Shift"][index % 3],
      attendanceRecord: { "2025-03-01": "Present", "2025-03-02": "Absent" },
      performanceScore: 80 + (index % 10),
      targetAssigned: 90 + index * 2,
      targetAchieved: 85 + index * 2,
      emergencyContact: { name: `Emergency Contact ${index + 5}`, phone: `07${index + 5}-2222222` },
      supervisorID: `S00${index + 5}`
    }))
  ];

  return (
    <div className="p-5 bg-Honeydew">
      <div className="grid grid-cols-2 gap-3">
        <div className="">
        <AttendancePieChart employees={sampleEmployees} />
        </div>
        <div className="">
        <EmployeeBarChart employees={sampleEmployees} />
        </div>
        <div className="col-span-2">
        <EmployeeTable employees={sampleEmployees} />
        </div>
       
       
      
      </div>
    </div>
  );
};

export default Dashboard;
